"""Portable painted shading: deterministic image maps and prototype-local UVs.

Authoring only. Image fields are sampled directly into PNGs, rather than keeping
procedural shader nodes that cannot travel with a GLB. Packed copies keep sources
self-contained; category-local PNGs remain available for texture painting.
"""
import math

import bpy
import numpy as np

import geometry as g
import art_style as style

VERSION = style.PAINTED_VERSION
family = style.material_family


def image_map(name, values, directory, *, data=False):
    existing = bpy.data.images.get(name)
    if existing:
        return existing
    height, width = values.shape[:2]
    image = bpy.data.images.new(name, width=width, height=height, alpha=False)
    image.colorspace_settings.name = style.TEXTURES.data_space if data else style.TEXTURES.color_space
    rgba = np.ones((height, width, 4), dtype=np.float32)
    rgba[:, :, :3] = values[:, :, None] if values.ndim == 2 else values
    if not data:
        # Generated byte images store encoded pixels, unlike float image buffers.
        rgb=rgba[:, :, :3]
        rgba[:, :, :3]=np.where(rgb<=.0031308,rgb*12.92,1.055*np.maximum(rgb,0)**(1/2.4)-.055)
    image.pixels.foreach_set(rgba.ravel())
    directory.mkdir(parents=True, exist_ok=True)
    image.filepath_raw = str(directory / (name + '.png'))
    image.file_format = 'PNG'
    image.save()
    image.pack()
    return image


def fields(kind, size):
    v, u = np.mgrid[0:size, 0:size].astype(np.float32) / (size - 1)
    # Broad harmonic washes stay coherent within faces; fine variation is quiet.
    wash = (np.sin(u * 13 + v * 7) + .55 * np.sin(u * 29 - v * 17)
            + .3 * np.cos(u * 53 + v * 37)) / 1.85
    grain = np.sin(u * 171 + v * 51) * np.cos(u * 67 - v * 109)
    value = .87 + .10 * wash + .022 * grain
    height = .006 * wash
    tint = np.ones((size, size, 3), dtype=np.float32)
    if kind == 'crystal':
        value = .83 + .15 * wash + .13 * v
        tint[:, :, 0] = .74 + .42 * v
        tint[:, :, 1] = .84 + .30 * np.sin(v * math.pi)
        tint[:, :, 2] = 1.02
        # Narrow internal glints taper instead of becoming luminous tube meshes.
        for x, y in [(.18, .29), (.48, .61), (.76, .42), (.64, .86)]:
            streak = np.exp(-((u - x - .08 * (v - y)) / .009) ** 2
                            - ((v - y) / .065) ** 2)
            value += .28 * streak
        shards = np.sin(u * 24 + v * 31 + np.sin(v * 8))
        value += .055 * np.tanh(shards * 4)
        edge=np.exp(-(np.sin((u-.532-.01*v)*math.pi*style.GEOMETRY.crystal_sides)/.045)**2)
        value += .65*edge*np.clip(v*7,0,1)
    elif kind in ('leaf', 'moss'):
        value = .67 + .31 * v + .07 * wash
        vein = np.exp(-((u - .5) / .018) ** 2) * np.sin(v * math.pi)
        branches = np.exp(-(np.sin(v * 30 - abs(u - .5) * 26) / .16) ** 2)
        value += .06 * vein + .018 * branches
        tint[:, :, 0] = .83 + .23 * v
        tint[:, :, 2] = 1.04 - .20 * v
        height += .012 * vein + .004 * branches
    elif kind == 'wing':
        # Soft eye markings and veins stay in the map, with darker wing roots.
        value = .66 + .32 * v + .07 * wash
        veins = np.exp(-(np.sin((u - .5) * 15 / (.25 + v)) / .13) ** 2)
        eye = np.minimum(np.sqrt(((u - .26) / .14) ** 2 + ((v - .68) / .15) ** 2),
                         np.sqrt(((u - .70) / .13) ** 2 + ((v - .58) / .14) ** 2))
        value -= .32 * np.exp(-((eye - .78) / .20) ** 2)
        value += .19 * np.exp(-(eye / .42) ** 2) - .035 * veins
        tint[:, :, 0] = .83 + .27 * v
        tint[:, :, 2] = 1.09 - .12 * v
    elif kind == 'fur':
        value = .79 + .17 * v + .06 * wash + .012 * grain
        tint[:, :, 0] = .95 + .07 * v
    elif kind == 'wood':
        lines = np.sin(u * 124 + .8 * np.sin(v * 15) + .3 * wash)
        knots = np.exp(-((u - .36) / .13) ** 2 - ((v - .64) / .09) ** 2)
        rings = np.sin(np.sqrt(((u - .36) * 7) ** 2 + ((v - .64) * 15) ** 2) * 23)
        value += .045 * lines - .035 * knots * rings
        value *= .83 + .17 * v
        height += .008 * lines
    elif kind in ('stone', 'plaster'):
        tint[:, :, 0] = .94 + .06 * v
        tint[:, :, 2] = 1.03 - .06 * v
        value *= .84 + .16 * v
        if kind == 'stone':
            crack = np.zeros_like(u)
            for x, y in [(.28, .42), (.71, .74)]:
                path = x + .016 * np.sin(v * 47) + .023 * np.sin(v * 19)
                crack += np.exp(-((u - path) / .0025) ** 2
                                - ((v - y) / .11) ** 6)
            value -= .11 * crack
            height -= .011 * crack
    elif kind == 'mushroom':
        value = .76 + .22 * v + .06 * wash
        tint[:, :, 0] = .95 + .18 * v
        tint[:, :, 1] = 1.1 - .16 * v
        height *= .3
    elif kind == 'ground':
        value = .91 + .10 * wash + .035 * grain
        tint[:, :, 0] = .94 + .05 * wash
        height *= .4
    elif kind == 'gill':
        value = .74 + .24 * v + .045 * wash
        value += .028 * np.sin(u * 85)
    elif kind == 'roof':
        value = .80 + .19 * v + .06 * wash
        height += .002 * grain
    elif kind == 'water':
        value = .91 + .065 * np.sin(v * 42 + np.sin(u * 8))
        height *= .2
    elif kind == 'window':
        value=.70+.27*np.exp(-((u-.44)/.40)**2-((v-.60)/.48)**2)
        tint[:,:,0]=1.02;tint[:,:,1]=.89+.12*v
    return value, tint, height


def texture_material(mat, directory):
    if mat.get('painted_finish') == VERSION:
        return
    kind = family(mat.name)
    if not kind or not mat.use_nodes:
        return
    shader = next((n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED'), None)
    if shader is None:
        return
    base = style.material_name(mat.name)
    size = style.TEXTURES.size_for(kind)
    value, tint, height = fields(kind, size)
    color = np.array(shader.inputs['Base Color'].default_value[:3], dtype=np.float32)
    linear = np.clip(color * value[:, :, None] * tint, 0, 1)
    if kind == 'wing' and base != 'wing_border':
        v, u = np.mgrid[0:size, 0:size].astype(np.float32) / (size - 1)
        tips = {'wing_cyan': (.68, .38, .76), 'wing_coral': (.98, .73, .32),
                'wing_moon': (.53, .47, .73), 'wing_lilac': (.28, .69, .75)}
        tip = np.array(style.srgb_to_linear(tips[base]), dtype=np.float32)
        blend = np.clip((v - .46) * 1.35, 0, .63)
        linear = linear * (1 - blend[:, :, None]) + tip * blend[:, :, None] * value[:, :, None]
        eye = np.minimum(np.sqrt(((u - .26) / .14) ** 2 + ((v - .68) / .15) ** 2),
                         np.sqrt(((u - .70) / .13) ** 2 + ((v - .58) / .14) ** 2))
        center = np.exp(-(eye / .42) ** 4) * .74
        seed = np.array(style.srgb_to_linear((.94, .83, .57)), dtype=np.float32)
        linear = linear * (1 - center[:, :, None]) + seed * center[:, :, None]
    if kind == 'crystal':
        v,u=np.mgrid[0:size,0:size].astype(np.float32)/(size-1)
        def linear_color(rgb):
            rgb=np.array(rgb,dtype=np.float32)
            return np.where(rgb<=.04045,rgb/12.92,((rgb+.055)/1.055)**2.4)
        blue=linear_color((.09,.37,.96));cyan=linear_color((.09,.86,1))
        violet=linear_color((.59,.31,.95));highlight=linear_color((.42,.98,1))
        blend=np.clip(.52+.34*np.sin(u*19+v*8)+.16*np.sin(v*17-u*7),0,1)
        if base=='crystal_blue':blend=np.clip(blend-.16,0,1)
        elif base=='crystal_light':blend=np.clip(blend+.12,0,1)
        linear=blue*(1-blend[:,:,None])+cyan*blend[:,:,None]
        purple=np.exp(-((u-.78)/.19)**2)*(.30+.50*v)
        if base in ('crystal_purple','crystal_lilac'):purple=.45+.40*blend
        linear=linear*(1-purple[:,:,None])+violet*purple[:,:,None]
        edge=np.exp(-(np.sin((u-.532-.01*v)*math.pi*style.GEOMETRY.crystal_sides)/.045)**2)
        linear=linear*(1-.72*edge[:,:,None])+highlight*.72*edge[:,:,None]
        linear*=np.clip(value,.78,1.15)[:,:,None]
    # Fields stay linear until image_map encodes the generated byte image.
    albedo = image_map('painted_' + base + '_color', linear, directory)
    nodes, links = mat.node_tree.nodes, mat.node_tree.links
    tex = nodes.new('ShaderNodeTexImage'); tex.image = albedo
    tex.label = 'Painted gradients and fine surface marks'; tex.location = (-540, 240)
    links.new(tex.outputs['Color'], shader.inputs['Base Color'])
    roughness = float(shader.inputs['Roughness'].default_value)
    rough = np.clip(roughness + style.TEXTURES.roughness_variation * (value - value.mean()), style.TEXTURES.roughness_min, style.TEXTURES.roughness_max)
    rough_image = image_map('painted_' + kind + '_roughness', rough, directory, data=True)
    tex = nodes.new('ShaderNodeTexImage'); tex.image = rough_image; tex.location = (-540, 0)
    links.new(tex.outputs['Color'], shader.inputs['Roughness'])
    if kind in style.NORMAL_FAMILIES:
        dv, du = np.gradient(height)
        normal = np.stack((-du * size * style.TEXTURES.normal_relief, -dv * size * style.TEXTURES.normal_relief, np.ones_like(du)), axis=-1)
        normal /= np.linalg.norm(normal, axis=-1, keepdims=True)
        normal_image = image_map('painted_' + kind + '_normal', normal * .5 + .5, directory, data=True)
        tex = nodes.new('ShaderNodeTexImage'); tex.image = normal_image; tex.location = (-540, -240)
        node = nodes.new('ShaderNodeNormalMap'); node.location = (-250, -240)
        links.new(tex.outputs['Color'], node.inputs['Color'])
        links.new(node.outputs['Normal'], shader.inputs['Normal'])
    emission = float(shader.inputs['Emission Strength'].default_value)
    if emission > 0:
        # Retain dark areas and the shape's shading underneath its internal glow.
        strength = (.60 + .70 * np.clip(value - .75, 0, .45))
        if kind=='crystal':
            # Dim colored body, strong thin highlights: preserve internal depth.
            strength=.12+.30*np.clip(value-.75,0,.45)+.90*edge*np.clip(v*7,0,1)
        glow = image_map('painted_' + base + '_emission', linear * strength[:, :, None], directory)
        tex = nodes.new('ShaderNodeTexImage'); tex.image = glow; tex.location = (-540, 460)
        links.new(tex.outputs['Color'], shader.inputs['Emission Color'])
    mat['painted_finish'] = VERSION
    mat['texture_family'] = kind


def forest_material(mat, directory):
    """Explicit opt-in refresh of owned woodland color/roughness/emission maps.

    Preserve slots, UVs, normal maps and mesh data. Named-image caching is bypassed
    with a scoped profile prefix; the default apply/build path is unchanged.
    Call only after preserving and inspecting generated/manual channel ownership.
    """
    base = style.material_name(mat.name)
    if base not in style.FOREST_MATERIALS or mat.get('forest_finish') == style.FOREST.version:
        return False
    shader = next(n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
    spec = style.FOREST_MATERIALS[base]
    kind = family(base)
    size = style.TEXTURES.size_for(kind)
    value, tint, _ = fields(kind, size)
    v, u = np.mgrid[0:size, 0:size].astype(np.float32) / (size - 1)
    color = np.array(style.srgb_to_linear(spec.color), dtype=np.float32)
    shadow = np.array(style.srgb_to_linear(style.FOREST.shadow), dtype=np.float32)
    root_blend = style.FOREST.gill_root_blend if kind == 'gill' else style.FOREST.root_blend
    roots = root_blend * (1 - v) ** 2
    linear = color * (1 - roots[:, :, None]) + shadow * roots[:, :, None]
    tip = (style.FOREST.cap_blue_tip if base == 'mushroom_blue' else
           style.FOREST.cap_purple_tip if base == 'mushroom_purple' else
           style.FOREST.gill_tip if kind == 'gill' else
           spec.color if base == 'forest_leaf_lilac' else style.FOREST.leaf_tip)
    tips = style.FOREST.tip_blend * v ** 2
    linear = linear * (1 - tips[:, :, None]) + np.array(style.srgb_to_linear(tip)) * tips[:, :, None]
    linear = np.clip(linear * value[:, :, None] * tint, 0, 1)
    rough = np.clip(spec.roughness + style.FOREST.roughness_variation * (value - value.mean()),
                    style.TEXTURES.roughness_min, style.TEXTURES.roughness_max)
    prefix = style.FOREST.version + '_' + base

    def bind(channel, values, suffix, data=False):
        image = image_map(prefix + '_' + suffix, values, directory, data=data)
        socket = shader.inputs[channel]
        if socket.is_linked and socket.links[0].from_node.type == 'TEX_IMAGE':
            socket.links[0].from_node.image = image
        else:
            node = mat.node_tree.nodes.new('ShaderNodeTexImage')
            node.image = image
            mat.node_tree.links.new(node.outputs['Color'], socket)

    bind('Base Color', linear, 'color')
    bind('Roughness', rough, 'roughness', data=True)
    shader.inputs['Base Color'].default_value = (*color, 1)
    shader.inputs['Roughness'].default_value = spec.roughness
    shader.inputs['Emission Strength'].default_value = spec.emission
    mat.diffuse_color = (*color, 1)
    if spec.emission:
        # Gills retain a shaded lavender-gray root/body. Cyan is localized to
        # the upper stem and cap underside, not a uniformly luminous stalk.
        mask = np.clip((v - .62) / .38, 0, 1)
        mask = mask * mask * (3 - 2 * mask)
        bind('Emission Color', linear * mask[:, :, None], 'emission')
    mat['forest_finish'] = style.FOREST.version
    return True


def project_uv(obj):
    mesh = obj.data
    if mesh.uv_layers:
        return
    uv = mesh.uv_layers.new(name=style.TEXTURES.uv_name)
    points = np.array([tuple(vertex.co) for vertex in mesh.vertices])
    low, span = points.min(axis=0), np.maximum(np.ptp(points, axis=0), .001)
    long_axis = int(span.argmax())
    names = [family(mat.name) for mat in mesh.materials if mat]
    cylindrical = obj.name.startswith(('Faceted magical crystal', 'Broad faceted mushroom',
                                        'Curving luminous mushroom'))
    center = (points.min(axis=0) + points.max(axis=0)) * .5
    for poly in mesh.polygons:
        dominant = max(range(3), key=lambda axis: abs(poly.normal[axis]))
        axes = [axis for axis in range(3) if axis != dominant]
        if 'wood' in names and long_axis in axes:
            axes = [next(axis for axis in axes if axis != long_axis), long_axis]
        coords = []
        for index in poly.vertices:
            p = points[index]
            if cylindrical and abs(poly.normal.z) < .98:
                coords.append([math.atan2(p[1] - center[1], p[0] - center[0]) / math.tau + .5,
                               (p[2] - low[2]) / span[2]])
            else:
                coords.append([(p[axis] - low[axis]) / span[axis] for axis in axes])
        if cylindrical and max(p[0] for p in coords) - min(p[0] for p in coords) > .5:
            for p in coords:
                if p[0] < .5:
                    p[0] += 1
        for index, value in zip(poly.loop_indices, coords, strict=True):
            uv.data[index].uv = value


def apply(collection, category='environment'):
    directory = g.ROOT / 'sources' / category / 'textures'
    seen = set()
    for obj in collection.objects:
        if obj.type != 'MESH':
            continue
        if obj.data not in seen:
            project_uv(obj)
            seen.add(obj.data)
        for slot in obj.material_slots:
            if slot.material:
                texture_material(slot.material, directory)
    collection['modeling_stage'] = VERSION


def ground(collection, name, category='environment'):
    """Paint soft contact occlusion and local bounce onto receiving ground only."""
    bpy.context.view_layer.update()
    receivers = [obj for obj in collection.objects if obj.type == 'MESH' and
                 obj.name.startswith(('Standard hex meadow top', 'Meadow river bank', 'Hex meadow'))]
    if not receivers:
        return
    size = style.TEXTURES.ground_size
    v, u = np.mgrid[0:size, 0:size].astype(np.float32) / (size - 1)
    x, y = (u - .5) * (2*style.HEX.radius), (v - .5) * (2*style.HEX.radius)
    value, tint, _ = fields('ground', size)
    material = receivers[0].material_slots[0].material
    shader = next(n for n in material.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
    color = np.array(shader.inputs['Base Color'].default_value[:3])
    linear = color * value[:, :, None] * tint
    glow = np.zeros_like(linear)
    for obj in collection.objects:
        kind = obj.get('kit_asset', '')
        if not kind or obj.parent is None:
            continue
        pos = obj.matrix_world.translation
        scale = max(abs(c) for c in obj.matrix_world.to_scale())
        if pos.z > .15:
            continue
        if any(word in kind for word in ('boulder', 'monolith', 'mushroom', 'crystal', 'tree_snag',
                                         'hollow_tree', 'spiral_tree', 'jackalope', 'snail', 'lantern_flower')):
            radius = (.21 if 'crystal' in kind else .28) * scale
            shadow = np.exp(-((x - pos.x) ** 2 + (y - pos.y) ** 2) / max(.02, radius ** 2))
            linear *= (1 - style.TEXTURES.contact_strength * shadow[:, :, None])
        if any(word in kind for word in ('crystal', 'mushroom', 'lantern')):
            radius = (.44 if 'crystal' in kind else .31) * scale
            spill = np.exp(-((x - pos.x) ** 2 + (y - pos.y) ** 2) / max(.03, radius ** 2))
            light = np.array((.09, .29, .34) if 'lantern' not in kind else (.38, .15, .035))
            linear += spill[:, :, None] * light * style.TEXTURES.bounce_strength
            glow += spill[:, :, None] * light * style.TEXTURES.bounce_emission
    directory = g.ROOT / 'sources' / category / 'textures'
    mat = material.copy(); mat.name = 'Painted receiving ground ' + name
    mat['receiving_ground']=True
    nodes, links = mat.node_tree.nodes, mat.node_tree.links
    shader = next(n for n in nodes if n.type == 'BSDF_PRINCIPLED')
    tex = nodes.new('ShaderNodeTexImage')
    tex.image = image_map('painted_' + name + '_ground_color', np.clip(linear, 0, 1), directory)
    links.new(tex.outputs['Color'], shader.inputs['Base Color'])
    tex = nodes.new('ShaderNodeTexImage')
    tex.image = image_map('painted_' + name + '_ground_emission', glow, directory)
    links.new(tex.outputs['Color'], shader.inputs['Emission Color'])
    shader.inputs['Emission Strength'].default_value = 1
    for obj in receivers:
        uv = obj.data.uv_layers.active
        for poly in obj.data.polygons:
            for loop in poly.loop_indices:
                p = obj.matrix_world @ obj.data.vertices[obj.data.loops[loop].vertex_index].co
                uv.data[loop].uv = (p.x / (2*style.HEX.radius) + .5, p.y / (2*style.HEX.radius) + .5)
        obj.material_slots[0].link = 'OBJECT'
        obj.material_slots[0].material = mat
