"""Package a static catalog from existing exports; no Blender or runtime backend."""
import hashlib
import json
import shutil
import tempfile
from pathlib import Path

from .index import CatalogIndex, ROOT, write_json
from .ui_assets import publish_ui

MARKER = '.asset-catalog-build'


def build_site(output='dist/catalog', include_sources=False, root=ROOT):
    root = Path(root).resolve()
    output = Path(output)
    output = (root / output).resolve() if not output.is_absolute() else output.resolve()
    if root.is_relative_to(output):
        raise ValueError('Build output cannot contain the repository')
    for folder in ('catalog', 'exports', 'sources', 'tools', 'ui', 'docs', '.git', '.github'):
        protected = root / folder
        if output.is_relative_to(protected) or protected.is_relative_to(output):
            raise ValueError(f'Build output overlaps repository inputs: {folder}')
    if output.exists() and not (output.is_dir() and (output / MARKER).is_file()):
        raise ValueError(f'Refusing to replace a directory not created by this builder: {output}')

    data = CatalogIndex(root).build()
    problems = data['warnings'] + [f"{asset['id']}: {asset['error']}"
                                  for asset in data['assets'] if asset['error']]
    if not data['assets']:
        problems.append('No exported GLBs found')
    if problems:
        raise ValueError('Cannot build catalog:\n' + '\n'.join(problems))

    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='catalog-build-', dir=output.parent) as directory:
        stage = Path(directory)
        (stage / MARKER).write_text('Generated by tools.asset_catalog.build_site\n')
        (stage / '.nojekyll').touch()
        (stage / 'catalog').mkdir()
        for name in ('catalog.js', 'catalog.css'):
            shutil.copyfile(root / 'catalog' / name, stage / 'catalog' / name)
        # Copy real files, not symlinks; Pages artifacts forbid links.
        for path in sorted((root / 'catalog/vendor').rglob('*')):
            if not path.is_file():
                continue
            if not path.resolve().is_relative_to(root / 'catalog/vendor'):
                raise ValueError(f'Viewer dependency escapes vendor directory: {path}')
            destination = stage / path.relative_to(root)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, destination)
        html = (root / 'catalog/index.html').read_text()
        html = html.replace('content="api/catalog"', 'content="catalog.json"')
        html = html.replace('content="live"', 'content="static"')
        (stage / 'index.html').write_text(html)
        ui = [asset for asset in data['assets'] if asset.get('kind')]
        if ui:
            publish_ui(root, stage, ui)
        copied = {}
        for asset in data['assets']:
            if asset.get('kind'):
                continue  # Native runtime/dependency records are already content hashed.
            if asset['source'] and not include_sources:
                asset['source'] = None
                asset['source_excluded'] = True
            for key in ('model', 'thumbnail', 'preview', 'reference', 'source'):
                record = asset[key]
                if not record:
                    continue
                relative = record['path']
                suffix = Path(relative).suffix.lower()
                allowed = {'.glb'} if key == 'model' else {'.blend'} if key == 'source' else {
                    '.png', '.jpg', '.jpeg', '.webp', '.gif', '.avif', '.svg'}
                if suffix not in allowed:
                    raise ValueError(f'Unexpected file type for {key}: {relative}')
                if relative not in copied:
                    source = root / relative
                    destination = stage / relative
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copyfile(source, destination)
                    with destination.open('rb') as stream:
                        copied[relative] = hashlib.file_digest(stream, 'sha256').hexdigest()
                # Content hashes make builds reproducible across fresh checkouts.
                record['version'] = copied[relative]
        data.pop('revision')
        data['revision'] = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()
        write_json(stage / 'catalog.json', data)
        if output.exists():
            shutil.rmtree(output)
        stage.rename(output)
    return data
